name: test_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - rangehttpserver
      - aiohttp
      - flask
      - appdirs
      - dask
      - jinja2
      - numpy
      - pyyaml
      - requests
      - msgpack-numpy
      - pytest-cov
      - coveralls
      - pytest
      - fsspec
      - intake-parquet
      - zarr
      - notebook
      - panel
      - hvplot
      - bokeh
      - dask
      - h5netcdf
      - h5py < 3.15  # due to HDF error, see netcdf4 Issue #1438
      - intake
      - netcdf4
      - pip
      - pydap
      - pytest
      - rasterio
      - s3fs
      - scikit-image
      - xarray
      - zarr
      - moto
      - toolz
      - pre-commit
      - siphon
