name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - aiohttp
  - flask
  - appdirs
  - dask
  - jinja2
  - numpy
  - pyyaml
  - requests
  - msgpack-numpy
  - pytest-cov
  - coveralls
  - pytest
  - fsspec
  - intake-parquet
  - zarr
  - notebook
  - panel
  - hvplot
  - bokeh
  - dask
  - h5netcdf
  - intake
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - s3fs
  - scikit-image
  - xarray
  - zarr
  - moto
  - rangehttpserver
  - pre-commit
  - sqlalchemy
  - python-duckdb
  - pytest-postgresql
  - psycopg
  - siphon
  - postgresql
