name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - aiohttp
  - flask
  - appdirs
  - dask
  - jinja2
  - numpy
  - pyyaml
  - requests
  - msgpack-numpy
  - pytest
  - fsspec
  - intake-parquet
  - zarr
  - notebook
  - panel
  - hvplot
  - bokeh
  - dask
  - intake
  - pip
  - pytest
  - rasterio
  - s3fs
  - h5netcdf
  - xarray
  - zarr
  - moto
  - httpx
  - typer
  - pydantic >=1.8
  - sqlalchemy
  - click
  - rangehttpserver
  - pre-commit
  - sqlalchemy
  - python-duckdb
  - pytest-postgresql
  - psycopg
  - siphon
  - postgresql
