name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - aiohttp
  - flask
  - appdirs
  - dask
  - jinja2
  - numpy
  - pyyaml
  - requests
  - msgpack-numpy
  - pytest
  - fsspec
  - intake-parquet
  - zarr
  - notebook
  - panel
  - hvplot
  - bokeh
  - dask
  - pip
  - pydap
  - pytest
  - s3fs
  - moto
